root@PatchPilotServer:~# ./server_test.sh 
==============================
     Testing System Dependencies
==============================
🔍  Checking if Python 3 is installed...
✔️  Python 3 is installed.
🔍  Checking if pip is installed...
✔️  pip is installed.
🔍  Checking if curl is installed...
✔️  curl is installed.
🔍  Checking if unzip is installed...
✔️  unzip is installed.
🔍  Checking if PostgreSQL is installed...
✔️  PostgreSQL is installed.
🔍  Checking if systemd is installed...
✔️  systemd is installed.
==============================
     Testing PostgreSQL Setup
==============================
🔍  Checking if PostgreSQL password file exists...
❌  PostgreSQL password file '/opt/patchpilot_server/postgresql_pwd.txt' not found! Please check your installation or setup steps.
🔍  Testing PostgreSQL connection...
==============================
     Testing Virtual Environment
==============================
🔍  Checking if virtual environment directory exists...
✔️  Virtual environment directory exists.
🔍  Checking if pip is installed inside the virtual environment...
✔️  pip is installed in the virtual environment.
🔍  Checking if Flask is installed in the virtual environment...
❌  Flask is NOT installed in the virtual environment. Try running 'pip install flask' inside the virtual environment.
🔍  Checking if psycopg2 is installed in the virtual environment...
❌  psycopg2 is NOT installed in the virtual environment. Try running 'pip install psycopg2' inside the virtual environment.
==============================
     Testing Repository Download
==============================
🔍  Testing GitHub repository download...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  285k    0  285k    0     0   933k      0 --:--:-- --:--:-- --:--:--  936k
✔️  Repository ZIP file downloaded.
🔍  Testing if the downloaded file is a valid ZIP file...
❌  ZIP file is corrupted or incomplete. The download may have failed. Please check the download.
