[package]
name = "patchpilot_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json", "diesel_sqlite"] }
diesel = { version = "2.0", features = ["sqlite", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.9"
chrono = "0.4"
psutil = "5.9.0"
