[package]
name = "rust_patch_client"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-service = { version = "0.4", optional = true }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simplelog = "0.11"
anyhow = "1.0"
sysinfo = { version = "0.28", optional = true }
lazy_static = "1.4"

[features]
default = []
windows = ["windows-service"]
unix = ["sysinfo"]

[[bin]]
name = "rust_patch_client"
path = "src/main.rs"

[[bin]]
name = "patchpilot_updater"
path = "src/patchpilot_updater.rs"
