[package]
name = "rust_patch_client"
version = "0.1.0"

[dependencies]
windows-service = { version = "*", optional = true }
reqwest = { version = "*", features = ["blocking", "json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
log = "*"
simplelog = "*"
anyhow = "*"
sysinfo = { version = "*", optional = true }
lazy_static = "*"

[features]
default = []
windows = ["windows-service"]
unix = ["sysinfo"]

[[bin]]
name = "rust_patch_client"
path = "src/main.rs"

[[bin]]
name = "patchpilot_updater"
path = "src/patchpilot_updater.rs"
